### PR TITLE
Updating to latest dependencies to address reported CVEs

### PR DESCRIPTION
**Pull request by setchy**
There were a number of old dependencies being used which contained Common Vulnerabilities and Exposures (CVEs) as reported by tools like Snyk

This pull request is to update as many of these dependencies as possible to bring them up to the latest compatible version so that most of the CVEs are resolved.

### CODE REVIEW

**Comment by setchy** [comment]
@IvanGoncharov @RomanHotsiy - do you think you'd be able to take a look into this PR when convenient?

**Comment by setchy** [comment]
@FluorescentHallucinogen - are you able to take a look over this PR at your convenience

**Comment by FluorescentHallucinogen** [comment]
@setchy I'm not a maintainer of this project and I have no rights to merge pull requests here, I'm just a contributor like you, have created a few pull requests, and they are not merged too, see e.g. #157. ¯\_(ツ)_/¯

**Comment by setchy** [comment]
Ah, my apologies @FluorescentHallucinogen - odd indeed

**Comment by setchy** [comment]
@IvanGoncharov @RomanHotsiy ?

**Comment by klausi** [comment]
There are git conflicts now. Can you resolve those so that the maintainers have an easier time merging?

**Comment by setchy** [comment]
Looking at the latest updates on master it seems this PR is now redundant.  Closing

**Comment by setchy** [comment]
I believe all that is needed is a new release of this codebase

**Comment by joaogarin** [comment]
Hello, Still having issues with this dependency. Any idea what the problem might be? https://github.com/APIs-guru/graphql-voyager/blob/master/package.json#L74 Material ui still looks like on version 3 and from this PR looks like was being updated to 4.x

I still get a vulnerability report for materal ui core.

**Comment by setchy** [comment]
Re-opening .... updated to latest minor and patch versions of all dependencies

**Comment by setchy** [comment]
@klausi - done 👍

**Comment by setchy** [comment]
@RomanHotsiy @IvanGoncharov - would you mind having a look over this PR please.

**Comment by klausi** [comment]
Hm, any reason you closed this? I think the update still needs to be done?

**Pull request closed without merging**
