### PR TITLE
[bugfix] introspection: check for the existence of a node

### PR DESCRIPTION
**Pull request by mralexrabota**
When this type: 

```graphql
type PageConnection {
  edges: [PageEdge!]!
  pageInfo: PageInfo!
}

union PageEdge = 
  PageEdge__Product 
  | PageEdge__Product_Dynamic 
  | PageEdge__SubProduct
  | PageEdge__Entity

type PageEdge__Product {
  cursor: String
  node: ITableNode__Product!
}
...
```

So all crash with error (can not read prop node of undefined). I 
added a check for the existence of a field.

### CODE REVIEW

**Comment by mralexrabota** [comment]
@IvanGoncharov @RomanGotsiy

**Comment by IvanGoncharov** [comment]
@mralexrabota ATM, I'm traveling from GraphQL Asia back to Ukraine but I will try to review it ASAP.
In general, this change makes total sense but I there few things I like to fix.

**Comment by mralexrabota** [comment]
@IvanGoncharov what should i fix?)

**Comment by IvanGoncharov** [comment]
@RayZik I removed `package-lock.json` and also cleanup code a bit.
Merged and released as `1.0.0-rc.27`.
Can you please test it?

**Comment by RayZik** [comment]
@IvanGoncharov Yes, I can) I have a question, why did you remove the package-lock.json file?)

**Comment by RayZik** [comment]
@IvanGoncharov It works) 

- Dependency `graphql-voyager": "^1.0.0-rc.27`
 
- Result:
Selection_035

**Comment by IvanGoncharov** [comment]
>  I have a question, why did you remove the package-lock.json file?)

We use yarn so we track dependencies using `yarn.lock`:
https://github.com/APIs-guru/graphql-voyager/blob/master/yarn.lock

> It works)

Thanks for confirmation 👍

**Comment by RayZik** [comment]
@IvanGoncharov Oh, I didn't see yarn.lock...now I understand) Thx for the explanation)

**Pull request merged**
